Repository aadilmughal786/jwt-auth, pull requests merged in 2023-09, with the labels that each got.

#1 [JA-1] Add Pull Request (PR) Template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, enhancement

#2 [JA-2] Add codeql.yml
  .github/workflows/codeql.yml
Labels: enhancement

#3 [JA-3] Enforce Lowercase File Naming with Dashes
  .github/pull_request_template.md
  jwt.md
  readme.md
Labels: enhancement

#4 [JA-4] Invalid codeql.yaml
  .github/workflows/codeql.yml
Labels: bug

#7 Revert "[JA-5] Add eslint.yml"
  .github/workflows/eslint.yml
Labels: invalid

#8 Add middleware and models
  .gitignore
  app/middlewares/auth-jwt.js
  app/middlewares/index.js
  app/middlewares/verify-sign-up.js
  app/models/index.js
  app/models/role.model.js
  app/models/user.model.js
  app/seed/role.seed.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#9 [ JA-9 ] Add controller
  app/controllers/auth.controller.js
  app/controllers/user.controller.js
  app/middlewares/auth-jwt.js
  app/middlewares/verify-sign-up.js
  app/routes/auth.routes.js
  app/routes/user.routes.js
  readme.md
  server.js
Labels: enhancement

#10 [JA-10] improve app architecture
  app/constants/index.js
  app/controllers/auth.controller.js
  app/middlewares/auth-jwt.js
  app/middlewares/verify-sign-up.js
  app/models/index.js
  app/models/role.model.js
  app/models/user.model.js
  app/routes/auth.routes.js
  app/routes/user.routes.js
  app/seed/role.seed.js
  package-lock.json
  package.json
  server.js
  status-code.md
Labels: enhancement

#11 [JA-11] Add colors in morgan logging
  morgan-config.js
  package-lock.json
  package.json
  server.js
Labels: enhancement

#16 Prettier Configuration
  .github/workflows/codeql.yml
  .prettierrc.json
  app/constants/index.js
  app/controllers/auth.controller.js
  app/controllers/user.controller.js
  app/middlewares/auth-jwt.js
  app/middlewares/index.js
  app/middlewares/verify-sign-up.js
  app/models/index.js
  app/models/role.model.js
  app/models/user.model.js
  app/routes/auth.routes.js
  app/routes/user.routes.js
  app/seed/role.seed.js
  jwt.md
  morgan-config.js
  package-lock.json
  package.json
  readme.md
  server.js
Labels: enhancement

#17 Add eslint support
  .eslintrc.json
  package-lock.json
  package.json
  server.js
Labels: enhancement

#18 Create eslint.yml
  .eslintrc.json
  .github/workflows/codeql.yml
  .github/workflows/eslint.yml
Labels: enhancement

#15 feat: add husky and commitlint in devDependencies
  .commitlintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .lintstagedrc.json
  package-lock.json
  package.json
Labels: enhancement

#21 Sample Config
  app/config.sample/auth.config.js
  app/config.sample/client.config.js
  app/config.sample/db.config.js
  app/config.sample/server.config.js
  readme.md
Labels: enhancement

#23 Add banner image
  .husky/commit-msg
  .husky/pre-commit
  assets/jwt-auth-banner.png
  readme.md
Labels: enhancement

#34 feat : Create LICENSE
  LICENSE
Labels: documentation

#33 Feature: Add workflow for test
  .github/workflows/test.yml
  app/app.js
  app/config.sample/db.config.js
  app/server.js
  package.json
Labels: enhancement, test cases
